name: prepare-build
author: Luna
description: Prepare build environment
inputs:
  web:
    description: 'Whether to prepare the web build environment'
    required: true
    default: 'true'
runs:
  using: 'composite'
  steps:
    - run: mkdir -p easytier-gui/dist
      shell: bash

    - name: Setup Frontend Environment
      if: ${{ inputs.web == 'true' }}
      uses: ./.github/actions/prepare-pnpm
      with:
        build_filter: './easytier-web/*'
